### PR TITLE
Account for packages starting with @.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3)

### CODE REVIEW

**Review by pcorpet — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3)* status: LGTM missing

*[a discussion](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-LSPlGDYEdx8DJpj7Yt2:-LSPlGDYEdx8DJpj7Yt3:b-de6ptq) (no related file):*
Please create a CHANGELOG

---
___
*[src/index.js, line 10 at r1](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-LSPlJf66eI7k0tYwJGJ:-LSPlJf66eI7k0tYwJGK:b-qjeru2) ([raw file](https://github.com/bayesimpact/yarn-lazy-lock/blob/a8f6e1de5af8ba0f0f257c8a808eb5248948929d/src/index.js#L10)):*
> ```JavaScript
> // Read lockfile.
> const locks = lockfile.parse(fs.readFileSync('yarn.lock', 'utf-8')).object
> const packages = _.groupBy(Object.keys(locks), pkg => pkg.replace(/^@*(.*)@.*$/, '$1'))
> ```

I think this was here for a reason, especially now there is ambiguity on what we capture when we match '@babel/core@github://....' Can you check some doc and link it here please?

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3)* status: LGTM missing

___
*[src/index.js, line 10 at r1](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-LSPlJf66eI7k0tYwJGJ:-LSPyBV9CDcqzeJzA1Yg:b-ngocj9) ([raw file](https://github.com/bayesimpact/yarn-lazy-lock/blob/a8f6e1de5af8ba0f0f257c8a808eb5248948929d/src/index.js#L10)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think this was here for a reason, especially now there is ambiguity on what we capture when we match '@babel/core@github://....' Can you check some doc and link it here please?
</blockquote></details>

I've never seen that pattern in yarn.lock (@github), and I found no doc on lock syntax :(. If the ambiguity you talk about is which `@` will be picked up by the regexp, `*` is actually greedy, so the first group will match everything until the LAST `@` (which is precisely what we want... except if there's an @ in the version, which can only happen with BasicAuth urls).

**Review by pcorpet — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-:-LSQF7bA5UAp_7DPDBLc:bnfp4nl)* status: Unresolved discussions

___
*[CHANGELOG.md, line 3 at r2](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-LSQEs_nEFCK7tOA1yv7:-LSQEs_nEFCK7tOA1yv8:b-pnxlph) ([raw file](https://github.com/bayesimpact/yarn-lazy-lock/blob/c5f1c77054fe69dae28c138122b76ebbe6e64e37/CHANGELOG.md#L3)):*
> ```Markdown
> ## 0.1.2 (November 28, 2018)
> 
> * Now works with packages starting with `@`
> ```

Add an EOL.
___
*[src/index.js, line 10 at r1](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-LSPlJf66eI7k0tYwJGJ:-LSQF4bG4Gsfonakega_:b-v5odho) ([raw file](https://github.com/bayesimpact/yarn-lazy-lock/blob/a8f6e1de5af8ba0f0f257c8a808eb5248948929d/src/index.js#L10)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

I've never seen that pattern in yarn.lock (@github), and I found no doc on lock syntax :(. If the ambiguity you talk about is which `@` will be picked up by the regexp, `*` is actually greedy, so the first group will match everything until the LAST `@` (which is precisely what we want... except if there's an @ in the version, which can only happen with BasicAuth urls).
</blockquote></details>

OK, no need to comment.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3)* status: Unresolved discussions

___
*[CHANGELOG.md, line 3 at r2](https://reviewable.io/reviews/bayesimpact/yarn-lazy-lock/3#-LSQEs_nEFCK7tOA1yv7:-LSRfbCCAsXz7n_HtG8Y:b-896fix) ([raw file](https://github.com/bayesimpact/yarn-lazy-lock/blob/c5f1c77054fe69dae28c138122b76ebbe6e64e37/CHANGELOG.md#L3)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Add an EOL.
</blockquote></details>

Done.

**Pull request merged**
